#!/usr/bin/env python3
"""Generate frozen float32 coefficient tables for the STM32 kernel.

The output uses hexadecimal C float literals and includes a SHA-256 over the
little-endian float words. Generation happens on the host; target init copies
the selected const table to DTCM and step() never calls libm.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import math
import struct
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Manifest:
    name: str
    q: float
    h: float
    memory: int


MANIFESTS = {
    "lorenz": Manifest("lorenz", 0.995, 0.005, 2000),
    "rossler": Manifest("rossler", 0.970, 0.010, 1000),
    "chen": Manifest("chen", 0.900, 0.005, 2000),
}


def f32(value: float) -> float:
    return struct.unpack("<f", struct.pack("<f", value))[0]


def c_hex(value: float) -> str:
    return f"{f32(value).hex()}f"


def append_word(digest, value: float) -> None:
    digest.update(struct.pack("<f", f32(value)))


def efork_coefficients(q: float):
    g1 = math.gamma(1.0 + q)
    g2 = math.gamma(1.0 + 2.0 * q)
    g3 = math.gamma(1.0 + 3.0 * q)
    g1_sq = g1 * g1
    g2_sq = g2 * g2
    denominator = 2.0 * g2_sq - g3
    c2 = (1.0 / (2.0 * g1)) ** (1.0 / q)
    c3 = (1.0 / (4.0 * g1)) ** (1.0 / q)
    return (
        c2,
        c3,
        1.0 / (2.0 * g1_sq),
        (g1_sq * g2 + 2.0 * g2_sq - g3)
        / (4.0 * g1_sq * denominator),
        -g2 / (4.0 * denominator),
        (8.0 * g1**3 * g2_sq - 6.0 * g1**3 * g3 + g2 * g3)
        / (g1 * g2 * g3),
        2.0 * g1_sq * (4.0 * g2_sq - g3) / (g2 * g3),
        -8.0 * g1_sq * denominator / (g2 * g3),
    )


def stable_difference(lower: float, exponent: float) -> float:
    if lower == 0.0:
        return 1.0
    return math.exp(exponent * math.log(lower)) * math.expm1(
        exponent * math.log1p(1.0 / lower)
    )


def efork_tables(manifest: Manifest):
    q = f32(manifest.q)
    coefficients = tuple(f32(value) for value in efork_coefficients(q))
    c2, c3 = coefficients[:2]
    exponent = 1.0 - q
    inverse_gamma = 1.0 / math.gamma(2.0 - q)
    tables = []
    for offset in (0.0, c2, c3):
        tables.append(
            [
                f32(
                    stable_difference(index + offset, exponent)
                    * inverse_gamma
                )
                for index in range(manifest.memory)
            ]
        )
    return coefficients, tables


def gl_table(manifest: Manifest):
    q = f32(manifest.q)
    q_plus_one = f32(q + f32(1.0))
    weights = [f32(1.0)]
    for index in range(1, manifest.memory + 1):
        factor = f32(f32(1.0) - f32(q_plus_one / f32(index)))
        weights.append(f32(weights[-1] * factor))
    return weights


def emit_array(name: str, values: list[float]) -> None:
    print(f"static const float {name}[{len(values)}] = {{")
    for start in range(0, len(values), 4):
        row = ", ".join(c_hex(value) for value in values[start : start + 4])
        print(f"    {row},")
    print("};")
    print()


def generate(manifest: Manifest, method: str) -> None:
    digest = hashlib.sha256()
    q = f32(manifest.q)
    h = f32(manifest.h)
    h_to_q = f32(math.pow(h, q))
    append_word(digest, q)
    append_word(digest, h)
    append_word(digest, h_to_q)
    digest.update(struct.pack("<I", manifest.memory))

    print("/* Generated by tests/generate_tables.py; do not hand-edit. */")
    print('#include "fractional_chaos.h"')
    print()

    if method == "efork":
        coefficients, tables = efork_tables(manifest)
        for value in coefficients:
            append_word(digest, value)
        for stage, values in enumerate(tables):
            for value in values:
                append_word(digest, value)
            emit_array(
                f"fc_{manifest.name}_efork_w{stage + 1}",
                values,
            )
        digest_hex = digest.hexdigest()
        coefficient_text = ", ".join(c_hex(value) for value in coefficients)
        print(
            f"const fc_precomputed_tables_t "
            f"FC_{manifest.name.upper()}_EFORK_TABLES = {{"
        )
        print("    FC_METHOD_EFORK3,")
        print(f"    {c_hex(q)}, {c_hex(h)}, {manifest.memory}u,")
        print(f"    {c_hex(h_to_q)},")
        print(f"    {{{coefficient_text}}},")
        print(
            "    {"
            f"fc_{manifest.name}_efork_w1, "
            f"fc_{manifest.name}_efork_w2, "
            f"fc_{manifest.name}_efork_w3"
            "},"
        )
        print("    NULL,")
        print(f'    "{digest_hex}"')
        print("};")
    else:
        values = gl_table(manifest)
        for value in values:
            append_word(digest, value)
        emit_array(f"fc_{manifest.name}_gl_w", values)
        digest_hex = digest.hexdigest()
        print(
            f"const fc_precomputed_tables_t "
            f"FC_{manifest.name.upper()}_GL_TABLES = {{"
        )
        print("    FC_METHOD_GL_CAPUTO,")
        print(f"    {c_hex(q)}, {c_hex(h)}, {manifest.memory}u,")
        print(f"    {c_hex(h_to_q)},")
        print("    {0.0f, 0.0f, 0.0f, 0.0f, "
              "0.0f, 0.0f, 0.0f, 0.0f},")
        print("    {NULL, NULL, NULL},")
        print(f"    fc_{manifest.name}_gl_w,")
        print(f'    "{digest_hex}"')
        print("};")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("system", choices=sorted(MANIFESTS))
    parser.add_argument("method", choices=("efork", "gl"))
    parser.add_argument(
        "--output",
        type=Path,
        help="archivo C de salida; se utiliza stdout cuando se omite",
    )
    arguments = parser.parse_args()
    if arguments.output is None:
        generate(MANIFESTS[arguments.system], arguments.method)
        return 0

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    with arguments.output.open("w", encoding="utf-8", newline="\n") as stream:
        with contextlib.redirect_stdout(stream):
            generate(MANIFESTS[arguments.system], arguments.method)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
